/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/
#description "converts ASCs binary file formats to the new plaintext formats"
#mandatoryq  "FILES [...]"
c / configfile  string           "Use given configuration file"
r / verbose     int 0 [0..10]    "Set verbosity level to x (0..10)"
