/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/   
#mandatoryq "ARCHIVEFILE [...]"
#description "extracts the contents of ASC archive files."
q / quiet     flag    "Disable informational output"
