/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/
#description "builds a ASC graphicset from single PCX files"
#mandatoryq  "GRAPHICSET.GFX IMAGES.PCX [...]"
c / configfile  string           "Use given configuration file"
