/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/   
#description "generates PCX images of ASC and Battle Isle maps"
#mandatoryq "FILE [...]"
c / configfile  string           "Use given configuration file"
r / verbose     int 0 [0..10]    "Set verbosity level to x (0..10)"
d / outdir      string {"data/"}  "Place images in given directory"
