/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/   
#mandatoryq "DATAFILE [...] ARCHIVEFILE"
#description "constructs an ASC archive from the data files."
q / quiet     flag    "Suppress informational output"
