/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/
#description "extracts all graphics from ASC vehicle type files"
/* #mandatoryq  "TANK2ICSET.GFX IMAGES.PCX [...]" */
c / configfile  string           "Use given configuration file"
