/* 
   This is the file from which the command line parsing code of ASC is 
   generated by genparse ( http://genparse.sourceforge.net ) 
*/
#description "lists the IDs of all ASC objects"
c / configfile  string           "Use given configuration file"
r / verbose     int 0 [0..10]    "Set verbosity level to x (0..10)"
