javac AbsoluteConstraints.java
javac AbsoluteLayout.java
javac RLEHeader.java
javac RLEHeader2.java
javac RLEPackage.java
javac SingleWeapon.java
javac UnitWeapon.java
javac PK.java
javac Weapon.java
javac Weapons.java
javac ClassBound.java
javac ErrorMessage.java
javac MakeCheckIntRangeField.java
javac SgStream.java
javac Unit.java
javac UnitEditor.java
javac MainWindow.java
