/*
 * MainWindow.java
 *
 * Created on 7. November 1999, 01:36
 */
 


/** 
 *
 * @author  Viper
 * @version 
 */

public class MainWindow extends javax.swing.JFrame {

  String tUnitPath = "C:\\";  
  public javax.swing.JList unitFileList;
  String unitFile[];
  ErrorMessage errMsg;
    
  /** Creates new form JFrame */
  public MainWindow() {
    initComponents ();
    setTitle("ASC File Editor");
    
    jTxtFieldUnitPath.setText (tUnitPath);
          
    unitFileList = new javax.swing.JList();
    unitFileList.setSelectionMode(new javax.swing.DefaultListSelectionModel().SINGLE_SELECTION);
    jScrollPaneUnitFiles.getViewport().setView(unitFileList);
    selUnitFiles();
    
    errMsg = new ErrorMessage(jLabelErrorMessage);
        
    pack ();
  } 

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    getContentPane ().setLayout (new AbsoluteLayout ());
    addWindowListener (new java.awt.event.WindowAdapter () {
      public void windowClosing (java.awt.event.WindowEvent evt) {
        exitForm (evt);
      }
    }
    );

    jTabbedPaneMain = new javax.swing.JTabbedPane ();
    jTabbedPaneMain.setPreferredSize (new java.awt.Dimension(520, 382));

    jPanelUnits = new javax.swing.JPanel ();
    jPanelUnits.setLayout (new AbsoluteLayout ());
    jPanelUnits.setPreferredSize (new java.awt.Dimension(370, 310));

    jTxtFieldUnitPath = new javax.swing.JTextField ();
    jTxtFieldUnitPath.setBorder (new javax.swing.border.TitledBorder(
    new javax.swing.border.EtchedBorder(), "UnitPath", 1, 2,
    new java.awt.Font ("Arial", 0, 10)));
    jTxtFieldUnitPath.setText ("c:\\");
    jTxtFieldUnitPath.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jTxtFieldUnitPathActionPerformed (evt);
      }
    }
    );
    jTxtFieldUnitPath.addFocusListener (new java.awt.event.FocusAdapter () {
      public void focusLost (java.awt.event.FocusEvent evt) {
        jTxtFieldUnitPathFocusLost (evt);
      }
    }
    );

    jPanelUnits.add (jTxtFieldUnitPath, new AbsoluteConstraints (10, 250, 350, 50));

    jButtonEditUnit = new javax.swing.JButton ();
    jButtonEditUnit.setText ("Edit Unit");
    jButtonEditUnit.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jBtnUnitEditorActionPerformed (evt);
      }
    }
    );

    jPanelUnits.add (jButtonEditUnit, new AbsoluteConstraints (380, 150, 130, 60));

    jButtonBrowsePath = new javax.swing.JButton ();
    jButtonBrowsePath.setText ("Browse");
    jButtonBrowsePath.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonBrowsePathActionPerformed (evt);
      }
    }
    );

    jPanelUnits.add (jButtonBrowsePath, new AbsoluteConstraints (380, 260, 130, 30));

    jScrollPaneUnitFiles = new javax.swing.JScrollPane ();

    jPanelUnits.add (jScrollPaneUnitFiles, new AbsoluteConstraints (10, 10, 350, 230));

    jButtonNewUnit = new javax.swing.JButton ();
    jButtonNewUnit.setText ("New Unit");
    jButtonNewUnit.addActionListener (new java.awt.event.ActionListener () {
      public void actionPerformed (java.awt.event.ActionEvent evt) {
        jButtonNewUnitActionPerformed (evt);
      }
    }
    );

    jPanelUnits.add (jButtonNewUnit, new AbsoluteConstraints (380, 50, 130, 60));

    jTabbedPaneMain.addTab ("Units", jPanelUnits);

    jPanelTechnologies = new javax.swing.JPanel ();
    jPanelTechnologies.setLayout (new AbsoluteLayout ());

    jTabbedPaneMain.addTab ("Technologies", jPanelTechnologies);


    getContentPane ().add (jTabbedPaneMain, new AbsoluteConstraints (0, 0, 620, 360));

    jLabelErrorMessage = new javax.swing.JLabel ();
    jLabelErrorMessage.setBorder (new javax.swing.border.EtchedBorder());


    getContentPane ().add (jLabelErrorMessage, new AbsoluteConstraints (0, 370, 620, 40));

  }//GEN-END:initComponents

private void jButtonNewUnitActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUnitActionPerformed
// Add your handling code here:    
  }//GEN-LAST:event_jButtonNewUnitActionPerformed

private void jTxtFieldUnitPathFocusLost (java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFieldUnitPathFocusLost
// Add your handling code here:
  String path;
      
   path = jTxtFieldUnitPath.getText ();
   if ( checkPath(path) != 0 ) {
      jTxtFieldUnitPath.setText (tUnitPath);
      errMsg.showMessage("Invalid Path !");
   } else {
     tUnitPath = path;
     selUnitFiles();
   } 
  }//GEN-LAST:event_jTxtFieldUnitPathFocusLost

private void jTxtFieldUnitPathActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldUnitPathActionPerformed
// Add your handling code here:
  String path;
      
   path = jTxtFieldUnitPath.getText ();
   if ( checkPath(path) != 0 ) {
      jTxtFieldUnitPath.setText (tUnitPath);        
      errMsg.showMessage("Invalid Path !");
   } else {
     tUnitPath = path;
     selUnitFiles();
   } 
  }//GEN-LAST:event_jTxtFieldUnitPathActionPerformed

private void jButtonBrowsePathActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowsePathActionPerformed
// Add your handling code here:
    String dir;    
    
    javax.swing.JFileChooser jFileCh;
    
    jFileCh = new javax.swing.JFileChooser(tUnitPath);
    
    jFileCh.setFileSelectionMode(jFileCh.DIRECTORIES_ONLY);
    if ( jFileCh.showOpenDialog(jButtonBrowsePath) ==  jFileCh.APPROVE_OPTION ) {
      dir = jFileCh.getSelectedFile().getAbsolutePath();
      jTxtFieldUnitPath.setText (dir);
      tUnitPath = dir;
      selUnitFiles();
    }  
  }//GEN-LAST:event_jButtonBrowsePathActionPerformed
  
private void jBtnUnitEditorActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUnitEditorActionPerformed
// Add your handling code here:
    int selection = unitFileList.getSelectedIndex();
    if (selection >= 0) {
      String selName = unitFile[selection];
      new UnitEditor (tUnitPath,selName,tUnit.LOAD,new UnitEditor("","",0,0).DISPOSE).show ();
    }
  }//GEN-LAST:event_jBtnUnitEditorActionPerformed

  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm

  private void selUnitFiles() {
    String AllFiles[];
    String ext;
    java.io.File f;
    int i = 0;
           
    f = new java.io.File(tUnitPath);
    AllFiles = f.list();
   
    for (int j = 0; j < AllFiles.length; j ++) {
      ext = getExtension(AllFiles[j]);
      if (ext != null)
        if (ext.compareTo("veh") == 0) {
          i++;
        }  
    }
        
    unitFile = new String[i];
    
    i=0;
    
    for (int j = 0; j < AllFiles.length; j ++) {
      ext = getExtension(AllFiles[j]);
      if (ext != null)
        if (ext.compareTo("veh") == 0) {
          unitFile[i] = AllFiles[j];
          i++;
        }  
    }     
    unitFileList.setListData(unitFile);
  }  
  
  public String getExtension(String filename) {
    int i = filename.lastIndexOf('.');
    if(i>0 && i<filename.length()-1) {
      return filename.substring(i+1).toLowerCase();
    };
    return null;
  }
  
  private int checkPath(String path) {
    java.io.File cFile = new java.io.File(path);
  
    if (cFile.isDirectory() == true) return 0;
    else return 1;
  }
  
  /**
  * @param args the command line arguments
  */
  public static void main (String args[]) {    
    new MainWindow ().show ();
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane jTabbedPaneMain;
  private javax.swing.JPanel jPanelUnits;
  private javax.swing.JTextField jTxtFieldUnitPath;
  private javax.swing.JButton jButtonEditUnit;
  private javax.swing.JButton jButtonBrowsePath;
  private javax.swing.JScrollPane jScrollPaneUnitFiles;
  private javax.swing.JButton jButtonNewUnit;
  private javax.swing.JPanel jPanelTechnologies;
  private javax.swing.JLabel jLabelErrorMessage;
  // End of variables declaration//GEN-END:variables
  public Unit tUnit;    
}