%define prefix /usr

Summary:	Advanced Strategic Command 
Name:		asc
Version:	1.9.5.4
Release:	6
Copyright:	GPL
Group:		X11/Games/Strategy
Source:		http://prdownloads.sourceforge.net/asc-hq/asc-source-%{version}-cvs.tar.gz
Source1:	buildings.con
Source2:	main.con
Source3:	mk1.con
Source4:	trrobj.con
Source5:	trrobj2.con
BuildPrereq:	SDL-devel >= 1.1.3, SDL_image-devel, SDL_mixer-devel, SDLmm-devel >= 0.1.8
Requires:	SDL >= 1.1.3, SDL_image, SDL_mixer, SDLmm >= 0.1.8
BuildRoot:	%{_tmppath}/%{name}-%{version}-root
%description
Advanced Strategic Command 

%prep
%setup -q -n %{name}
cp $RPM_SOURCE_DIR/*.con $RPM_BUILD_DIR/%{name}/data
./bootstrap

%build
#export CXXFLAGS="-O0 -g" \
./configure --prefix=%{prefix}
make
%install
make DESTDIR=$RPM_BUILD_ROOT install

%clean
rm -rf $RPM_BUILD_ROOT

%files

%defattr(-,root,root)
%{prefix}/*

%changelog

* Sun Dec 01 2001 <root@nase4>
- First spec autogenerated by rpmbuilder.



