#! /bin/sh

if test "X$1" = X--force; then
   set -x
   set -e
   ./bootstrap.versionmerge configure.in
   autoreconf -I /usr/local/share/aclocal/ 
else
   echo "You don't need to run bootstrap. Just run \"configure ; make\" "
fi
