.TH "asc_mount" "6" "1.15.0"
.SH "NAME"
asc_mount \- Advanced Strategic Command mount
.SH "SYNTAX"
.LP 
.B asc_mount [\fIoptions\fP] [\fIdatafiles\fP] [\fIarchivefile\fP]
.SH "DESCRIPTION"
.LP 
This program constructs ASC archive file from the data files. 
It is a part of Advanced Strategic Command game.
.br
.SH "OPTIONS"
.LP 
The following options are supported
.LP 
.TP 15
.B -q --quiet 
Disable informational output
.TP 15
.B -h --help
Display help information
.TP 15
.B -v --version
Output version
.PD
.SH "SEE ALSO"
.PP
asc (6),
asc_demount (6),
asc_makegfx (6),
asc_mapedit (6),
asc_weaponguide (6)
.PD
.SH "AUTHORS"
.LP 
The ASC game is developed by Martin Bickel <bickel@asc-hq.org>.
.br 
This man page was written by Bartosz Fenski <fenio@o2.pl> (some parts were
grabbed from Michael Moerz's work) for the Debian GNU/Linux distribution 
(but it may be used by others).

