##0502
Thunderlance HQ, Relnid: 
Herzlichen Gluekwunsch Commander

sie haben erstklassige Arbeit geliefert. Mit der Eroberung von Relnid und der Einnahme von Tarplona sind wir in der Lage effektiver gegen das Imperium vorzugehen. Denken sie aber nicht, dass es ab jetzt leichter wird. Das Imperium hat unsere Aktivitaeten wargenommen.
Im Moment streitet sich die Fuehrung noch wie sie gegen uns vorgenen wollen. Im Westen befinden sich zwei Fahrzeugfabriken, Dies muessen wir ausnutzen und weiter Stuetzpunkte erobern, um den mit Sicherheit zu erwartenden Gegenangriff entgegenzutreten. Sollten wir keinen Erfolg haben, so steht uns eine aussichtlose Schlacht bevor.


; try http://babelfish.altavista.com :-)

Viel Glueck
Commander

Objectives:
Capture both vehicle factories


##0503
Thunderlance HQ, Relnid: 
Herzlichen Gluekwunsch Commander

Im Depot haben wir zwei Artillerie-Einheiten gefunden. Mit Hilfe unseres Tanklaster vom Typ Alguins kînnen wir diese auftanken und gegen den Feind einsetzen !
; we found two artillery units.
; We can refuel them with our tanker vehicle and use them against the enemy

##0504
Thunderlance HQ, Relnid: 
Herzlichen Gluekwunsch Commander

Im Depot haben wir zwei Artillerie-Einheiten gefunden. 
Da wir leider den Tanklaster vom Typ Alguin verloren haben, mÅssen wir mit Treibstoff sehr sparsam umgehen. Aber vielleicht kînnen wir einige stark beschÑdigte Einheiten im Depot zurÅcklassen und den Treibstoff in die Artillerie umfÅllen.
; we found two artillery units.
; since we unfortuanatly lost out tanker vehicles, we have to be very careful with our fuel. Perhaps we can leave some badly damaged units behind in the depot and use their fuel for the artillerie