##0701
Thunderlance HQ, Relnid: 
Commander, unsere Truppen haben die Nordkueste der Insel Rogul erreicht. Oberste Prioritaet hat die Einnahme des Flughafens. Er muesste sich weit im Landesinneren befinden. 
Das Oberkommanda weisst Sie also an, einen Landungstrupp nach Rogul zu bringen und den Flughafen einzunehmen.

Leider gerieten unsere Landungsboot in ein Feld von Treibminen bzw. in die Reichweite der feindlichen Kuestenwache. Versuchen Sie sie zu retten um dann an Land weitere Befehle zu erhalten.  

Viel Glueck, Commander!

Objectives:
Capture airport

##0702
Thunderlance HQ, Relnid: 

Der Verlust der Landungsboote ist tragisch. Eine Landung an der Kueste von Rogul ist somit nicht mehr moeglich, versuchen Sie einen anderen Weg zu finden, um unsere verbliebenen Truppen
an Land zu bringen. Passen Sie auf, dass Sie den CRAB nicht verlieren. Die Mission waere beim Verlust dieses Schiffes gescheitert!

##0703
Thunderlance HQ, Relnid: 
Sehr gut, Commander!

Eine Fahrzeugfabrik ist eingenommen und unsere Truppen konnten sicher landen. Nach Verhoer des gefangen genommenen Fabrikdirektors haben wir die Information erhalten, dass sich suedlich der Fabrik ein groﬂes Minefeld befindet.
Leider haben wir mit Verlust der Landungsboote unsere Minenspaeher verloren, die dieses Problem haetten loesen koennen. Finden Sie einen Weg, die Minen zu beseitigen um weiter vorstossen zu koennen. Ein Versuch das Minenfeld trotz Warnung zu durchqueren, ist nicht ratsam!
Nach Angaben des Direktors befinden sich im Osten die zentrale Stromversorgung der Fabrik. Desweiteren liegen auf dem Weg ein Material- und Treibstofflager.
Versuchen Sie diese Gebaeude zu sichern, damit die Produktion in der Fabrik wieder beginnen kann. Wir werden Verstaerkungen brauchen.

##0705
Thunderlance HQ, Relnid: 
Gute Arbeit, 
die Transporter haben genug Material geladen, damit wir ein paar Einheiten produzieren koennen. Betanken Sie diesen und bringen Sie sie zur Fabrik!

##0704
Thunderlance HQ, Relnid: 
Gute Arbeit, 
das Treibstofflager ist bereits mit unserer Fabrik verbunden. Spritmangel unserer Truppen sollte daher kein Problem darstellen.

##0706
Thunderlance HQ, Relnid: 
Gute Arbeit, 
die Windgeneratoren liefern ausreichend Energie, damit unsere Fabrik mit Strom versorgt werden kann.

##0707
Thunderlance HQ, Relnid: 
Perfekt, Commander!
Wir haben jetzt alle noetigen Ressourcen um weitere Einheiten herzustellen. Vergessen Sie nicht ein paar Shock Trooper auszubilden, damit diese das suedliche Minenfeld raeumen koennen.

##0708
Thunderlance HQ, Relnid: 
Sehr gut, Commander!
Die erbeuteten Einheiten werden uns bei der Einnahme des Flughafens behilflich sein. Sie muessen nur noch aufgetankt werden.
 
