##0801
Thunderlance HQ, Relnid: 
Commander, wir haben geheime Dokumente ueber ein Forschungsprogramm des Imperiums entdeckt. Wie es aussieht wird in einer im Nordosten von Rogul errichteten Fabrik an einem neuen Waffensystem geforscht.
Unsere Wissenschaftler haben einen Transportzug in ein mobiles Labor umgewandelt. Bringen Sie den Transportzug in diese Waffenfabrik um die Daten für den Prototyp für uns zu gewinnen. Er darf nicht zerstoert werden!
Das Imperium hat von unseren Plaenen erfahren und bereits versucht unsere Fabrik zu sabotieren. Gluecklicherweise konnten wir den Anschlag vereiteln, jedoch ist die Fabrik nicht mehr an das Schienen- und Stromnetz angeschlossen.
Wir werden also eine neue Fabrik finden muessen um Verstaerkungen produzieren zu koennen. 

Achtung! Rogul wird durch den Fluss Gulog in zwei Seiten geteilt, welche nur mit einer Bruecke verbunden sind. Der Pegelstand des Flusses ist beunruhigend hoch. Beeilen Sie sich, da die Bruecke droht von den Wassermassen
weggespuehlt zu werden! 

Viel Glueck, Commander!

Objectives:
Transporttrain must reach northeastern factory

##0802
Thunderlance HQ, Relnid: 
Commander, in dem eroberten Bahnhof koennen wir unseren Transportzug sicher unterstellen bis die groesste Gefahr gebannt ist. Den Fahrplaenen zu Folge befindet sich im suedwesten eine Mine, im Nordosten ein im Sumpf bedindlicher Oelturm sowie
eine Fahrzeugfabrik und Windkraftwerke im Osten bzw. Suedosten. Mit der Einnahme dieser Einrichtungen haetten wir eine fundamentale Basis.

##0803
Thunderlance HQ, Relnid: 
Die Bruecke konnte den starken Wassermassen nicht laenger standhalten. 
Commander, finden Sie einen Weg die Bruecke zu reparieren um unseren Auftrag ausfuehren zu koennen.

##0804
Die Bruecke konnte den starken Wassermassen nicht laenger standhalten.
Mit den entdeckten Baufahrzeug sollten wir die Bruecke reparieren koennen. 

##0805
Thunderlance HQ, Relnid: 
Sehr gut, Commander!
Das gefundene Baufahrzeug sollte uns sehr nuetzlich sein. Schuetzen Sie es gut!

##0806
Thunderlance HQ, Relnid: 
Sehr gut, Commander!
Wir haben ein Baufahrzeug gefunden. Schuetzen Sie es gut!
Zwischenzeitlich ist der Pegelstand des Flusses auch leicht zurueckgegangen, so dass mit den Reparaturatbeiten an der Bruecke begonnen werden kann.

##0807
Thunderlance HQ, Relnid: 
Gute Arbeit, 
wir haben ein Hoovercraft erbeutet. Mit diesem koennen wir zwar den tiefen Fluss nicht ueberqueren, jedoch haben wir vom Bahnhofsvorsteher erfahren, dass sich im 
Westen eine kleine Insel befindet, auf dem stillgelegete Baufahrzeuge zu finden waeren.
