##0501
Thunderlance HQ, Relnid:

The time has come for us to make our move, commander. We have suffered under the iron fist of the Imperium for long enough. Now we must free the others who have suffered. We must systematically capture all of the Imperium's cities, factories, research centers, and other structures. Once we have succeeded, we shall be free forever.

The nearby town of Relnid is only weakly guarded at the moment. This is our chance to strike!


Objectives:
Capture Ralnid, Ralnid Warehouse and the Relnid Power Station
