##2000
#font02#Welcome to Advanced Strategic Command !#font01#
#aeinzug0##eeinzug20#
This tutorial will guide you through the game and show some of the features we have implemented in ASC.

The emphasis in these maps is not the armed conflict which is the central part of the game, because such a conflict would be quite uninteresting without any opponent. And we don't have any working artificial intelligence yet. 

These messages are beeing archived in the ASC internal mail system so you can always read them again. Move your mouse up to open the pull down menu, select #color1#messages#color0# / #color1#view received messages#color0# and then the message you want to read.

You can save the game at any time (except while reading these messages) by selecting #color1#game#color0# / #color1#save game#color0# from the pull down menu.

The tutorial will only be loaded the first three times you start ASC. To load it later select #color1#game#color0# / #color1#new campaign#color0# and select the TUTORIAL.MAP .

##2003
There are two branches in the Tutorial, one for beginners to ASC or Battle Isle and another one for those who have already played Battle Isle 2/3. 

You don't need to be an expert in Battle Isle to play the Bi3 tutorial, I just assume some basic understanding of the game.

##2004
You have two troopers on this map, one is called #color1#BI3 expert#color0#, the other #color1#Beginner#color0#. The name of the unit or building under the cursor is displayed in the marked field on the right.

The goal of this level is to conquer the building called #color1#ASC academy#color0#. The tutorial is selected by the unit you choose to perform this task.

##2005
To move a unit, select it with the cursor by a left click on the field. Then press the MOVE Button on the right and click on a marked field, in this case one that is part of the building left of the troopers.

Btw, there is tooltip help available on most areas of the user interface. Just hoover your mouse over the items and wait a second.

##2001
Well done.

You have selected the Battle Isle tutorial.

##2002
Well done.

You have selected the Beginner tutorial.


##2100
Welcome to the 2nd tutorial map.

Here you will be shown the major differences between Batte Isle and ASC.

You are playing the Red Player again. 
Blue is an ally who has reconnaisance units to help you seeing the map. 
Yellow is the enemy.

##2101
We are going to start with the user interface. As you have probably already noticed in the first map, all actions that can be performed with a selected unit are shown as buttons on right. Their function is displayed in the message line below. All have keyboard shortcuts, which are printed orange there.

You can control ASC in several different ways which you will probably find out anyway. I just want to point out the -in my opinion- most efficient and least obvious technique:

##2102
In this map there is a Battle Ship and an enemy patrol boat. The patrol boat is already damaged which you would see in the highlighted field if the cursor was standing over it.

The Battle Ship has two weapons with which it can shoot at neighbouring ships, the second one is more powerful (which is unusual). You can destroy the patrol boat with a single shot from the second weapon.

##2103
To do this, do the following:

The cursor is already standing on the Battle Ship. Select ATTACK either by pressing the A key or by pressing the attack button on the right.

The patrol boat will then be highlighted. Now click on the patrol boat with the mouse but keep the mouse key pressed !

You will see that the buttons from the right side occured under your mouse. If you released the mouse key without moving it then the first button would be executed. 
But while you keep the mouse key pressed, you can move the mouse to the right button. Before releasing it there take a look at the message line: You will see the exact outcome of the battle: enemy damage = 100% .

Try it out now. 
If it fails, just press #color1#End Turn#color0#.

##2104
Well done. 

I admit that these method of controlling ASC needs to get used to, but in my opinion it is worth it. 

##2105
You activated "end turn" before you destroyed the patrol boat. You can try this technique again any time. Just remember to keep your mouse key pressed...

##2106
Ok, now let us really begin with the gameplay differences.

In ASC there are 8 levels of height on which units can be. These levels of height are 
#eeinzug30#
- deep submerged
- submerged
- floating
- ground based
- low level flight
- medium level flight
- high level flight
- orbit
#eeinzug0#
They are displayed on the right and are currently highlighted. A red icon indicates the height the marked unit is on, and light gray icons show levels of height the unit is principially able to be on.

##2107
You cannot see enemy units or buildings that are submerged unless your units are equipped with a sonar.
The blue awacs do not have sonar, so they do not see the submerged building that is exactly eight fields east of your battle ship.
Scroll to the left to find a submarine you own. It is equipped with a sonar. So move it four fields to the left until you see the submarine base.

##2108
Ok, you have found it.
Now conquer it !

Unlike in Battle Isle, you can conquer neutral buildings like this one with ANY unit, not only with troopers.

But you have to be on the same level of height as the building. Since you probably don't have any movement left, press #color1#end turn#color0#. 
Then submerge with you sub by activating #color1#descent#color0#, and move into the building.

##2109
Ok, you conquered it.

Another category of units that heavily depend on the different levels of height are airplanes.

Scroll down to see a red delta shaped aircraft standing on a runway. 
Some way down there is a yellow transport airplane flying. It is quite damaged too. Shoot it down !

##2110
To do this, your fighter plane must first take off. Don't move with it on the runway, use the #color1#ascent#color0# function instead. 
The plane will need two fields to take off. 

By the way, you can recognize the height of a flying unit by the position of its shadow too.

##2111
The take off required a whole turn, you are just able to move one field further.
Next turn, you can reach the yellow transport and attack it. 

On the way there, you can try out that you are able to move a unit several time in a single turn if it has any movement left.

##2112
Ok.

To the south you have another airplane standing. It is a transport plane. Use it to conquer the tank factory far in the south.

But there are two problems involved:

The first one is that there is no runway on the island of the vehicle plant. And the trooper in your transport plane can not jump out of flying aircraft.

##2113
The second problem is that your airplane does not have enough fuel to fly that far.

The fuel is displayed in the bar that has just been marked.

##2114
But there is hope :-)

To the south there is another runway with a tanker vehicle which can refuel our aircraft.

And next to it there is a paratrooper standing. And guess what he can do?

##2115
So the course of actions to take is:
#eeinzug30##aeinzug40#
- #color1#ascend#color0# with your transport plane
- move it during the next turn on to the first field of the second runway.
- even one turn later land there (#color1#descent#color0#)

##2116
Now refuel the airplane and load the paratrooper into it.
Then head south to the factory.

By the way, it is possible to repair landed airplanes with a sinus.

##2117
Ok, move the paratrooper out of the plane. 
"Enter" the plane with the #color1#show loading#color0# function, select the paratrooper and #color1#move#color0# it out.
It cannot conquer the building in the same turn it landed.

##2118
Now try to move the transport plane back.
You will notice that it can not go back as fast as it came here. 

The reason is simple: Triggered by the conquering of the factory quite a strong wind has arisen. It is blowing from north to south.

Right click on the overview map to view the wind display.

##2119
You can also move the fighter plane to see how it is affected by the wind.

This level will end in five turns, so you have some time to experiment with the units here a bit.

And you can notice how the blue awacs start consuming fuel to keep flying on the field.


Have fun and see you in the next part of the tutorial :-)

##2200
Welcome to the 2nd tutorial map.

As you will probably already know, ASC is a turn based strategy games.

On each map are up to 8 players with different colors. In this tutorial map you play the red units. Blue is an ally who has reconnaisance units to help you seeing the map. Yellow is the enemy who should be eliminated.

##2201
You start with a single unit called #color1#Wiesel#color0#. It has 7 movement points which is displayed on the right side.
That means you can move 7 fields on road, or less on rougher terrain. You can move a unit several times a turn, as long as it has any movement points left.

Try it out. Move your unit on the road eastwards.

##2202
You don't have any movement left. So it is time to end your turn. Press the #color1#end turn#color0# button.

If there were other players - either human or AI - on the map, it would be their turn now. But we don't have an AI yet, so the other units do nothing and you will immediately be at the turn again.

##2203
There is a building to the east. As you can see by its gray 'dot' it is a neutral building which means no player owns it yet.

In ASC there are many different building types, for example vehicle factories or training centers. This one is a town in which another unit is standing.

Now conquer this town by moving your unit into it.

##2204
Well done.

Right now your unit from the start is inside your town. Press #color1#show loading#color0# to look into the town.

You will see your Wiesel as well as a #color1#heavy combat tank#color0#. The Wiesel cannot move any more, but you can move the tank out.

##2205
The only way from this peninsula is to drive between the mountains in the north.

##2206
But there is an enemy tank blocking the passage. 

Tanks are usually equipped with weapons and your one is no exception. The position where they are displayed has just been marked. Right clicking there reveals extensive information about the weapon systems.

You can see that your tank has two weapons:
#eeinzug30##aeinzug40#
- a cannon with a strength of 114 and 6 shots.
- a machine gun with a strength of 28 and 4 rounds of ammo.
#eeinzug0##aeinzug0#
So you can attack 10 times until the ammuntion of the tank is depleted.

To attack the yellow tank select #color1#attack#color0# and then the enemy tank.

##2207
The enemy is not yet destroyed but severly damaged.

Attacking or moving into buildings generally (ok, there are exceptions...) ends a units turn.

So you must end your turn again and attack a second time then.

##2208
Ok, the yellow tank has been destroyed.

But your tank got some damage too. The damage of a unit is shown on the right. Clicking on the bar shows the exact percentage of the damage in the message line.

Now, get your Wiesel out of the town and move north.

##2209
All units consume fuel to move. The bar that has just been marked shows the status of the units fuel tank. As you can see your Wiesel does not have much left.

##2210
You can also click on the field where the remaining movement is displayed to toggle between the movement you can do this turn and the movement you can do with the fuel you have.

##2211
Move along the road to the next town and conquer it too, since there is a tanker inside.

##2212
There are two ways of refuelling your Wiesel:

Either move your tanker and the Wiesel out next turn and use the refuel function of the tanker to transfer the fuel.

Or you can transfer the fuel from the tanker to the town and from there back to the Wiesel. This can be done on the #color1#ammunition transfer#color0# page that is activated by clicking on the second tab on the buttom of the town window.

After you have refuelled the Wiesel, follow the road to the north.

##2213
You have been playing for some time now, but I haven't told you yet what the goal of this level is.

If you scroll to the left you can see an Island with a building called #color1#Villa Deng#color0#. You must conquer this building. But it is not easy.

To cross the water, you need a ship. It can be build in the shipyard that you can see in the north. But you can not conquer it with the Wiesel.

Most buildings cannot be entered by all units. It would not be useful if ships could drive into aircraft hangar or if a long range bomber could enter an oil rig.

But there is one type of unit that can enter ALL buildings: troopers. They can be produced in the vehicle plant that you can see in the north west. Conquer it !

##2214
Until now the only thing we used buildings for was to store units in them.

Now we want to produce a unit. This cannot be done for free. We need resources to do it.

ASC uses three kinds of resources:
- energy
- material
- fuel

This map is played in the BI Resource Mode. That means that each player has a global pool for energy and another one for fuel where all buildings can get it from. Material is restricted to the buildings and you need transport vehicles or pipelines to transport it from one building to another. All buildings can produce any amount of resources per turn (wheather they do it or not is determined by the map designer).

In contrast to the BI Resource Mode we also have an ASC Resource Mode which is much move sophisticated and uses wind power plants, mining stations, etc. But this will be discussed in a later tutorial that has yet to be designed.

The available resources are shown in the second line of the building dialog box. As you can see there is 1000 energy, 750 material and 200 fuel available. This is enough to produce one trooper.

Build it (click on an empty field and select produce, then the trooper), move it out and conquer the shipyard with it.

##2215
Now where you have the shipyard, you can try to produce a transport ship. But it is grayed out since there are not enough resources available. By comparing the available resource on the top of the window and the required resources that are displayed in the message line you can see that there is insufficient energy.

But the vehicle plant produces 3000 energy per turn. So you have to wait one or two turns until you can build the transport ship.

When you have built it, move it out, but just one field !

##2216
To be able to conquer the 'Villa Deng' you have to load the trooper into the transport ship.

When you have done it, drive eastwards with the ship.

##2217
An enemy Battle Ship is blocking the passage. But there is a second shipyard which is owned by the yellow player too. Since it is no neutral building you cannot conquer it with every unit, only with troopers.

Move your transport next to the shipyards entry and conquer the building with your trooper.

##2218
There are two Battle Ships inside. Move them out.

Battle Ships are able to shoot over a distance of 6 fields!

Move them out and into shooting distance to the yellow Battle Ship.

##2219
Many units capable of range attacks cannot shoot when they have already moved in a turn. The Battle Ships are one of these units. So you have to end your turn before you can continue.

##2220
Perhaps you have already noticed that there is a difference between your two battle ships.

It is their experience. Experience is a very important factor in ASC since it allows units to shoot much stronger. The position where it is displayed has been marked.

Attacking a unit gives one point of experience. If the attacked unit can retalliate (which is only the case when it is attacked from a neighbouring unit) it gets one point of experience too.
Destroying a unit gives an additional point of experience.

One your battle ships has absolutely no experience while the other one has the maximum experience (which is 16 points). Notice how much damage they inflict on the enemy ship.

And take a look at the experience symbol of the inexperienced battle ship before and after the attack.

Then destroy the enemy ship entirely.

##2221
Ok, the rest of the level should be easy now.

Make sure your trooper is in your transport, move it then to the beginning of the road, unload your trooper and conquer the building.

##2222
Congratulations !

You finished the first real tutorial level.

##2240
Please turn back, this is dangerous territory !

To complete this tutorial, stick to the path described in the messages.

##2241
This is your the last warning...

Turn back!


##2300
Welcome to the 3rd tutorial map.

This map covers the levels of height, airplanes and view.

You are playing the Red Player again. 
Blue is an ally who has reconnaisance units to help you seeing the map. 
Yellow is the enemy.

##2301
We start again with the user interface. As you already know, all actions that can be performed with a selected unit are shown as buttons on right. Their function is displayed in the message line below. All have keyboard shortcuts, which are printed orange there.

You can control ASC in several different ways which you will probably find out anyway. I just want to point out the -in my opinion- most efficient and least obvious technique:

In this map there is a Battle Ship and an enemy patrol boat. The patrol boat is already damaged. 

The Battle Ship has two weapons with which it can shoot at neighbouring ships, the second one is more powerful (which is unusual). You can destroy the patrol boat with a single shot from the second weapon.

##2303
To do this, do the following:

The cursor is already standing on the Battle Ship. Select ATTACK either by pressing the A key or by pressing the attack button on the right.

The patrol boat will then be highlighted. Now click on the patrol boat with the mouse but keep the mouse key pressed !

You will see that the buttons from the right side occured under your mouse. If you released the mouse key without moving it then the first button would be executed. 
But while you keep the mouse key pressed, you can move the mouse to the right button. Before releasing it there take a look at the message line: You will see the exact outcome of the battle: enemy damage = 100% .

Try it out now. 
If it fails, just press #color1#End Turn#color0#.

##2304
Well done. 

I admit that these method of controlling ASC needs to get used to, but in my opinion it is worth it. 

##2305
You activated "end turn" before you destroyed the patrol boat. You can try this technique again any time. Just remember to keep your mouse key pressed...

##2306
Ok, now let us really begin.

In ASC there are 8 levels of height on which units can be. These levels of height are 
#eeinzug30#
- deep submerged
- submerged
- floating
- ground based
- low level flight
- medium level flight
- high level flight
- orbit
#eeinzug0#
They are displayed on the right and are currently highlighted. A red icon indicates the height the marked unit is on, and light gray icons show levels of height the unit is principially able to be on.

##2307
You cannot see enemy units or buildings that are submerged unless your units are equipped with a sonar.
The blue awacs do not have sonar, so they do not see the submerged building that is exactly eight fields east of your battle ship.

Scroll to the left to find a submarine you own. It is equipped with a sonar. So move it four fields to the left until you see the submarine base.

##2308
Ok, you have found it.
Now conquer it !

But you have to be on the same level of height as the building. Since you probably don't have any movement left, press #color1#end turn#color0#. 
Then submerge with you sub by activating #color1#descent#color0#, and move into the building.

##2309
Ok, you conquered it.

Another category of units that heavily depend on the different levels of height are airplanes.

Scroll down to see a red delta shaped aircraft standing on a runway. 
Some way down there is a yellow transport airplane flying. It is quite damaged too. Shoot it down !

##2310
To do this, your fighter plane must first take off. Don't move with it on the runway, use the #color1#ascent#color0# function instead. 
The plane will need two fields to take off. 

By the way, you can recognize the height of a flying unit by the position of its shadow too.

##2311
The take off required a whole turn, you are just able to move one field further.
Next turn, you can reach the yellow transport and attack it. 

On the way there, you can try out that you are able to move a unit several time in a single turn if it has any movement left.

##2312
Ok.

To the south you have another airplane standing. It is a transport plane. Use it to conquer the tank factory far in the south.

But there are two problems involved:

The first one is that there is no runway on the island of the vehicle plant. And the trooper in your transport plane can not jump out of flying aircraft.

The second problem is that your airplane is damged (like so many units in the tutorial...) and a yellow air defence guards the factory. It will shoot on anything that comes into range. And unless your transport plane is repaired it will be shot down.

##2314
But there is hope :-)

To the south there is another runway with a repair vehicle which can repair the aircraft.

And next to it there is a paratrooper standing. And guess what he can do?

##2315
So the course of actions to take is:
#eeinzug30##aeinzug40#
- #color1#ascend#color0# with your transport plane
- move it during the next turn on to the first field of the second runway.
- even one turn later land there (#color1#descent#color0#)

##2316
Now repair the airplane and load the paratrooper into it.
Then head south to the factory.

##2317
Ok, move the paratrooper out of the plane. 
"Enter" the plane with the #color1#show loading#color0# function, select the paratrooper and #color1#move#color0# it out.
It cannot conquer the building in the same turn it landed.

##2318
Now try to move the transport plane back.
You will notice that it can not go back as fast as it came here. 

The reason is simple: Triggered by the conquering of the factory quite a strong wind has arisen. It is blowing from north to south.

Right click on the overview map to view the wind display.

##2319
You can also move the fighter plane to see how it is affected by the wind.

This level will end in five turns, so you have some time to experiment with the units here a bit.

And you can notice how the blue awacs start consuming fuel to keep flying on the field.


Have fun and see you in the next part of the tutorial :-)

##2400
Welcome to the last Tutorial map which focuses on the various construction vehicles. There are 3 vehicles in ASC's unitset which can build things:
#aeinzug60##eeinzug30#
The #color1#building constructor#color0# builds buildings
The #color1#construction vehicle#color0# builds objects like roads, railroads, pipelines and ditches
And the #color1#forester#color0# plants and removes forests.
#aeinzug0##eeinzug0#

The goal of this level is to conquer the wind power plant in the east. 

In the first part you must reach the shipyard in the north which you can conquer with the nuclear submarine you have. But there are two battle ships with enabled reaction fire in the way. So you can not get near them until you destroy both of them.

A submarine would be the best unit to destroy them, since battle ships can not engage submerged submarines. But unfortunatly there is shallow water where you can not dive between your sub and the battle ships.

But your submarine is a nuclear submarine which is equipped with cruise missiles that can shoot farther than the battle ships. The ideal weapon - if you only had any ammo ...

##2401
So the submarine is useless at the moment. Lets look what other units you have:

A heavy combat tank and a forester. Nearby is a vehicle plant. The enemy troopers around it would not stand a chance against the tank, if it only could get there. It can not go through the wood.

But the forester can help. The only purpose of this unit is to plant or to remove wood. The function to fell an aisle is behind the #color1#build road, ...#color0# icon.

We are going to build quite a number of objects in this level. Different objects require different amounts of movement points to construct them. So after you have moved, not all objects may be available. Just end your turn then to have the full amount of movement points at your disposal.

##2402
Now free the entry of the factory and conquer it.

##2403
Inside there is a #color1#Wiesel#color0# and a #color1#construction vehicle#color0#. With the Wiesel you can conquer another factory to the north. 

##2404
Here you can build a #color1#building constructor#color0#. But there are no resources in this factory. Energy and fuel are globally available, only material is missing.

Incidantly, the first factory has enough of it. You only must get it from building to building. This can be done by constructing a pipeline with the construction vehicle. As you can see, you need to build a pipeline on only two fields to connect the buildings.

When you have done it, build the #color1#building constructor#color0# and move it to the end of the road.

[the next message will be triggered by any unit moving onto this field, so don't go there with another unit first]

##2405
As the name suggests you can construct buildings with the #color1#building constructor#color0#.

Build a shipyard. If you build it with the constructor standing on the end of the road, the shipyard will touch the vehicle plant so you don't have to build any more pipelines.

Then move you submarine inside, refuel it, and shoot the battle ships down. Be careful to keep more than 6 fields distance from them.

Since your submarine is only capable of carrying 2 cruise missiles, you have to go back to the harbour once.

##2406
Now head further north. You will notice quite a lot of destroyers standing around the shipyard. And as usually they will shoot on anything that comes into range. But fortunatly they don't have any range attack weapons.

Shooting them down would be way too much work. Since they can not shoot on submarines that are #color3#deep#color0# submerged, you can dive beneath them. Be careful not to surface next to a destroyer.

##2407
Ok.

Inside there is trooper. Follow the road and you will find a town.

##2408
Among other units you got a radar vehicle. Move it out and follow the road to its end.

##2409
As you can see, the road to the next island is interrupted. But you got another #color1#construction vehicle#color0# in the town. And there is a #color1#building constructor#color0# too.

The #color1#construction vehicle#color0# can also build bridges. But we first have to get rid of the yellow artilleries on this island. Without any combat units the only way to destroy them is to build a turret.

Turrets are immobile units, but non the less they count as vehicles. They can only be build on special turret foundations that have to be constructed with the #color1#construction vehicle#color0# first.

Turrets can shoot over a distance of 7 fields. So choose an appropriate loacation, build a turret foundation and a turret there. Then destroy all three enemy artilleries. While doing it you can easily see the effect of the experience gained by the turret.

You will have to refuel the turret with your #color1#ammuntion transport vehicle#color0# before it can shoot.

##2410
Now you can start building a bridge to conquer the next town.

##2411
On the end of the next bridge you can already see an enemy tank. You too got a tank in this town that is principially able to shoot the yellow tank down.

But at the moment your tank, without any experience, does not stand a chance against the enemy.

To increase the tanks experience you can use the #color1#training center#color0# on this island. 

Conquer it !

##2412
Training a unit consumes ammunition and allows it to gain two experience points per turn.

Train your tank five times, which requires 6 turns. Equip it then with ammo again and destroy the yellow tank. Note that it is NOT enough to just press #color1#refuel#color0# for refuelling, since the training center does not have any ammo and is unable to produce it (unlike the shipyard).


##2413
Now move your #color1#Wiesel#color0# across the bridge to the next island.

In the north, far beyond the map, the enemy has blown up a dam wall and a huge tidal wave is coming down the river toward the delta.

It is coming fast so hurry up !

##2414
That was close !

Now conquer the vehicle factory nearby.

##2415
Inside the factory there is a mine layer. It is able to spot, lay and remove mines. Laying mines would not be useful against an oppenent that is unable to move, but the other abilities might prove useful. But just find out yourself...

##2416
Congratulations!

You successfully completed the tutorial.

I hope you enjoyed it. You can further experiment with ASC by playing this or other maps in multiplayer mode.

Don't hestiate to play email games. It is generally much more interesting to play against human opponents than agains an AI. Just write an email to the mailing list ( see DOC/CONTACT.HTM how to subscribe there).


##2499
That was a minefield !

Perhaps you should be more careful next time.

At the end of each turn ASC automatically saves. Restore the last savegame and try again.
