##1111
Thunderlance HQ, Relnid:

The time has come for us to make our move, commander. We have suffered under the iron fist of the Imperium for long enough. Now we must free the others who have suffered. We must systematically capture all of the Imperium's cities, factories, research centers, and other structures. Once we have succeeded, we shall be free forever.

Your current mission briefing is as follows:
We have managed to take the town of Relnid. This will serve as our headquarters. An Imperium headquarters is nearby, residing in the town of Tarplona. This headquarters has dispatched an assault force to drive us out of Relnid, and stop our rebellion. You will have all of the troops we have accumulated so far at your disposal. You must stop their troops, and take Tarplona.  If you fail, commander, we will not get another chance. 

Good luck, and godspeed!
Lenlin Grinson, Thunderlance Briefing Officer

Objectives:
Capture Imperium buildings