##1111
Thunderlance HQ, Relnid:

We have managed to take the town of Relnid. This will serve as our headquarters. An Imperium headquarters is nearby, residing in the town of Tarplona. This headquarters has dispatched an assault force to drive us out of Relnid, and stop our rebellion. You will have all of the troops we have accumulated so far at your disposal. You must stop their troops, and take Tarplona.  If you fail, commander, we will not get another chance. 

Good luck, and godspeed!
Lenlin Grinson, Thunderlance Briefing Officer

Objectives:
Capture Imperium buildings