INCLUDE SETPAGES.INC

EXTRN _activegraphmodeparameters    : TActiveGraphModeParameters
EXTRN _hardwaregraphmodeparameters  : TActiveGraphModeParameters
EXTRN _activefontsettings           : TFontSettings
EXTRN _mouseparams                  : TMouseSettings
EXTRN _dpmscapabilities             : dword
EXTRN _actdpmsmode                  : dword
EXTRN _xlatbuffer                   : dword
EXTRN _handleractive                : dword
