//#define word unsigned short int
//#define Word word
#define pascal_byte char
//#define Byte byte
//#define Byte byte
typedef char* pchar;
#define integer signed short int
#define Integer integer
// #define nil NULL
// #define NIL nil
// #define pointer void*
// #define Pointer pointer
// #define boolean char
// #define Boolean boolean
// #define shortint signed char
// #define Shortint shortint
// #define false 0
// #define true 1
/*
#define blockread(a,b,c) fread(b,1,c,a)
#define seek(a,b) fseek(a,b,SEEK_SET)
#define inc(a) (a)++
#define dec(a) (a)--
#define fillchar (a,b,c) memset( &a, c, b)
*/
