libfiles = ..\basestrm.cpp ..\sgstream.cpp ..\misc.cpp ..\typen.cpp ..\vehicletype.cpp ..\buildingtype.cpp ..\libs\bzlib\libbz2.lib ..\loadbi3.cpp ..\palette.cpp ..\gameoptions.cpp ..\named.cpp ..\basegfx.cpp
files = weaponguide.cpp 
CC = bcc32 -DHEXAGON -D_WIN32_ -Dconverter -DminimalIO -D_NOASM_ -v -w-

WeaponGuide.exe: $(files) $(libfiles)
	$(CC) $(files) $(libfiles)

